# fly.toml app configuration file generated for deadlock-faceit-stats-main on 2025-05-11T04:29:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deadlock-faceit-stats-main'
primary_region = 'ord'

[build]

[processes]
app = "npm run start"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024